import Head from "next/head";

export default function Layout({title}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>{title}</title>
      </Head>
    </>
  );
}
